<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <Authors>Daniel Anderson</Authors>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/magna-nz/redis-near-cache</RepositoryUrl>
    <PackageProjectUrl>https://github.com/magna-nz/redis-near-cache</PackageProjectUrl>
    <PackageTags>redis;valkey;cache;client-side-caching;near-cache;client-tracking;stackexchange.redis;hybridcache</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>
</Project>
