<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <Authors>Daniel Anderson</Authors>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/magna-nz/redis-near-cache</RepositoryUrl>
    <PackageProjectUrl>https://github.com/magna-nz/redis-near-cache</PackageProjectUrl>
    <PackageTags>redis;valkey;cache;caching;client-side-caching;client-side-cache;near-cache;client-tracking;stackexchange.redis;hybridcache;idistributedcache;distributed-cache;memory-cache;l1-cache</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <Copyright>Copyright (c) Daniel Anderson</Copyright>
    <PackageReleaseNotes>https://github.com/magna-nz/redis-near-cache/releases</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Version>1.7.0</Version>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)docs/nuget-readme.md" Pack="true" PackagePath="/README.md" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)docs/icon.png" Pack="true" PackagePath="/" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>
</Project>
